# -*- coding: utf-8 -*-
"""apple_color2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mt66lgX76RZ5p-g3pRCn2Uh1m1_57fGM
"""

# ============================================================
# Apple colorization model: clean border 128 -> RGBA 512
#
# No border completion model.
# No rotation / no scaling / no translation augmentation.
#
# Input:
#   clean border image, [B, 1, 128, 128]
#
# Target:
#   color image, resized to 512x512
#   alpha generated from white background
#
# Output:
#   [B, 4, 512, 512]
#   RGB logits + alpha logit
#
# Dataset zip:
#   /content/drive/MyDrive/borderModel2/apple_ver1/color.zip
#
# Expected structure:
#   color/
#     color_dataset/
#       apple/
#         1.png
#         2.png
#     border_dataset/
#       apple/
#         1.png
#         2.png
# ============================================================

from google.colab import drive
drive.mount('/content/drive')

import os
import json
import random
import shutil
import zipfile
from pathlib import Path

import numpy as np
from PIL import Image

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader

import matplotlib.pyplot as plt
from tqdm.auto import tqdm


# ============================================================
# Basic config
# ============================================================

PROJECT_ROOT = Path("/content/drive/MyDrive/borderModel2/apple_ver1")

COLOR_ZIP_PATH = PROJECT_ROOT / "color.zip"
LOCAL_COLOR_ROOT = Path("/content/apple_color_data_clean_128to512")

EXP_DIR = PROJECT_ROOT / "experiments" / "exp_color_rgba_128to512_clean_v001"
CHECKPOINT_DIR = EXP_DIR / "checkpoints"
SAMPLE_DIR = EXP_DIR / "samples"
LOG_DIR = EXP_DIR / "logs"

for d in [EXP_DIR, CHECKPOINT_DIR, SAMPLE_DIR, LOG_DIR]:
    d.mkdir(parents=True, exist_ok=True)


CONFIG = {
    # I/O size
    "border_input_size": 128,
    "color_output_size": 512,

    # Data split
    "train_ratio": 0.8,
    "val_ratio": 0.1,
    "test_ratio": 0.1,
    "random_seed": 42,
    "reuse_existing_split": True,

    # Training
    # 512出力はメモリを使うため、まずはbatch_size=4推奨
    "batch_size": 4,
    "epochs": 80,
    "learning_rate": 1e-3,
    "weight_decay": 1e-4,
    "early_stopping_patience": 15,

    # Runtime
    "num_workers": 0,
    "use_amp": True,

    # Model
    "input_channels": 1,
    "output_channels": 4,
    "base_channels": 24,

    # Alpha target generation from white background
    "white_bg_threshold": 245,

    # Loss weights
    "rgb_loss_weight": 5.0,
    "alpha_bce_weight": 1.0,
    "alpha_dice_weight": 1.0,
    "background_rgb_weight": 0.0,

    # Inference / metric threshold
    "alpha_threshold": 0.5,

    # Zip handling
    "force_reextract_color_zip": False,
}

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
PIN_MEMORY = DEVICE.type == "cuda"

print("DEVICE:", DEVICE)
print("CUDA available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

random.seed(CONFIG["random_seed"])
np.random.seed(CONFIG["random_seed"])
torch.manual_seed(CONFIG["random_seed"])
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(CONFIG["random_seed"])

with open(EXP_DIR / "config.json", "w", encoding="utf-8") as f:
    json.dump(CONFIG, f, indent=2, ensure_ascii=False)


# ============================================================
# Extract color.zip
# ============================================================

if not COLOR_ZIP_PATH.exists():
    raise FileNotFoundError(f"color.zip not found: {COLOR_ZIP_PATH}")

if CONFIG["force_reextract_color_zip"] and LOCAL_COLOR_ROOT.exists():
    print("Removing existing extracted dir:", LOCAL_COLOR_ROOT)
    shutil.rmtree(LOCAL_COLOR_ROOT)

LOCAL_COLOR_ROOT.mkdir(parents=True, exist_ok=True)

already_extracted = len(list(LOCAL_COLOR_ROOT.rglob("*.png"))) > 0

if already_extracted and not CONFIG["force_reextract_color_zip"]:
    print("color.zip already extracted. Reusing:", LOCAL_COLOR_ROOT)
else:
    print("Extracting color.zip...")
    with zipfile.ZipFile(COLOR_ZIP_PATH, "r") as z:
        z.extractall(LOCAL_COLOR_ROOT)
    print("Extracted to:", LOCAL_COLOR_ROOT)

print("\nExtracted top-level:")
for p in LOCAL_COLOR_ROOT.iterdir():
    print(" ", p)


# ============================================================
# Find dataset directories
# ============================================================

def image_count(path: Path) -> int:
    count = 0
    for ext in ["*.png", "*.PNG", "*.jpg", "*.JPG", "*.jpeg", "*.JPEG", "*.webp", "*.WEBP"]:
        count += len(list(path.glob(ext)))
    return count


def find_dataset_dir(root: Path, target_parts: tuple[str, str]) -> Path:
    """
    Example:
      target_parts=("border_dataset", "apple")
      target_parts=("color_dataset", "apple")
    """
    candidates = []

    for p in root.rglob(target_parts[-1]):
        if not p.is_dir():
            continue

        parts = p.parts
        if len(parts) >= len(target_parts):
            if tuple(parts[-len(target_parts):]) == target_parts:
                candidates.append(p)

    if len(candidates) == 0:
        print("\nDirectories under extracted root:")
        for p in root.rglob("*"):
            if p.is_dir():
                print(p)
        raise FileNotFoundError(f"Could not find directory ending with: {target_parts}")

    best = max(candidates, key=image_count)

    print(f"\nFound {target_parts}: {best}")
    print("Image count:", image_count(best))

    return best


BORDER_DIR = find_dataset_dir(LOCAL_COLOR_ROOT, ("border_dataset", "apple"))
COLOR_DIR = find_dataset_dir(LOCAL_COLOR_ROOT, ("color_dataset", "apple"))

print("\nFinal dataset dirs:")
print("BORDER_DIR:", BORDER_DIR)
print("COLOR_DIR:", COLOR_DIR)


# ============================================================
# Pair collection
# ============================================================

def list_image_files(path: Path):
    exts = ["*.png", "*.PNG", "*.jpg", "*.JPG", "*.jpeg", "*.JPEG", "*.webp", "*.WEBP"]
    files = []
    for ext in exts:
        files.extend(path.glob(ext))
    return sorted(files)


def collect_pairs(border_dir: Path, color_dir: Path):
    border_list = list_image_files(border_dir)
    color_list = list_image_files(color_dir)

    print("\nBorder files found:", len(border_list))
    print("Color files found:", len(color_list))

    print("Border examples:", [p.name for p in border_list[:10]])
    print("Color examples:", [p.name for p in color_list[:10]])

    border_files = {p.stem: p for p in border_list}
    color_files = {p.stem: p for p in color_list}

    common_stems = sorted(
        set(border_files.keys()) & set(color_files.keys()),
        key=lambda x: int(x) if x.isdigit() else x
    )

    pairs = []
    for stem in common_stems:
        pairs.append({
            "name": f"{stem}.png",
            "stem": stem,
            "border_path": border_files[stem],
            "color_path": color_files[stem],
        })

    missing_in_color = sorted(set(border_files.keys()) - set(color_files.keys()))
    missing_in_border = sorted(set(color_files.keys()) - set(border_files.keys()))

    print("Matched pairs:", len(pairs))
    print("Missing in color:", len(missing_in_color))
    print("Missing in border:", len(missing_in_border))

    if missing_in_color:
        print("Missing in color examples:", missing_in_color[:10])
    if missing_in_border:
        print("Missing in border examples:", missing_in_border[:10])

    return pairs


all_pairs = collect_pairs(BORDER_DIR, COLOR_DIR)

if len(all_pairs) == 0:
    raise RuntimeError("No matched border/color pairs found.")


# ============================================================
# Utility functions
# ============================================================

def pil_rgb_to_tensor(img: Image.Image) -> torch.Tensor:
    arr = np.asarray(img).astype(np.float32) / 255.0
    arr = np.transpose(arr, (2, 0, 1))
    return torch.from_numpy(arr)


def pil_gray_mask_to_tensor(img: Image.Image) -> torch.Tensor:
    arr = np.asarray(img).astype(np.float32) / 255.0
    return torch.from_numpy(arr).unsqueeze(0)


def tensor_to_rgb_numpy(t: torch.Tensor) -> np.ndarray:
    x = t.detach().cpu().clamp(0, 1).numpy()
    return np.transpose(x, (1, 2, 0))


def tensor_to_gray_numpy(t: torch.Tensor) -> np.ndarray:
    return t.detach().cpu().clamp(0, 1).squeeze(0).numpy()


def make_checkerboard(h, w, tile=24):
    yy, xx = np.indices((h, w))
    board = ((yy // tile + xx // tile) % 2).astype(np.float32)
    board = 0.85 + board * 0.10
    return np.stack([board, board, board], axis=-1)


def alpha_composite_on_checker(rgb: np.ndarray, alpha: np.ndarray) -> np.ndarray:
    bg = make_checkerboard(rgb.shape[0], rgb.shape[1], tile=24)
    alpha3 = alpha[..., None]
    return rgb * alpha3 + bg * (1.0 - alpha3)


def load_border_image_as_line_pil(path: Path, out_size: int) -> Image.Image:
    """
    Source:
      white background + black line.

    Returned PIL:
      line = 255
      background = 0
    """
    img = Image.open(path).convert("L")

    if img.size != (out_size, out_size):
        img = img.resize((out_size, out_size), Image.NEAREST)

    arr = np.asarray(img)
    mask = (arr < 128).astype(np.uint8) * 255
    return Image.fromarray(mask).convert("L")


def create_rgb_and_alpha_from_color_image(
    path: Path,
    out_size: int,
    white_threshold: int,
) -> tuple[Image.Image, Image.Image]:
    """
    Color target:
      original RGB image with white background.
      resize to out_size.
      alpha = non-white area.
    """
    rgb = Image.open(path).convert("RGB")

    if rgb.size != (out_size, out_size):
        rgb = rgb.resize((out_size, out_size), Image.BICUBIC)

    arr = np.asarray(rgb)

    alpha = np.logical_not(
        (arr[:, :, 0] >= white_threshold) &
        (arr[:, :, 1] >= white_threshold) &
        (arr[:, :, 2] >= white_threshold)
    ).astype(np.uint8) * 255

    alpha_img = Image.fromarray(alpha).convert("L")
    return rgb, alpha_img


# ============================================================
# Split
# ============================================================

def build_or_load_split(pairs, exp_dir: Path):
    split_path = exp_dir / "split.json"

    if CONFIG["reuse_existing_split"] and split_path.exists():
        print("\nLoading existing split:", split_path)
        with open(split_path, "r", encoding="utf-8") as f:
            split_data = json.load(f)

        pair_dict = {x["stem"]: x for x in pairs}

        train_pairs = [pair_dict[stem] for stem in split_data["train"] if stem in pair_dict]
        val_pairs = [pair_dict[stem] for stem in split_data["val"] if stem in pair_dict]
        test_pairs = [pair_dict[stem] for stem in split_data["test"] if stem in pair_dict]

        return train_pairs, val_pairs, test_pairs

    rng = random.Random(CONFIG["random_seed"])
    pairs_copy = pairs[:]
    rng.shuffle(pairs_copy)

    n = len(pairs_copy)
    n_train = int(n * CONFIG["train_ratio"])
    n_val = int(n * CONFIG["val_ratio"])

    train_pairs = pairs_copy[:n_train]
    val_pairs = pairs_copy[n_train:n_train + n_val]
    test_pairs = pairs_copy[n_train + n_val:]

    with open(split_path, "w", encoding="utf-8") as f:
        json.dump(
            {
                "train": [x["stem"] for x in train_pairs],
                "val": [x["stem"] for x in val_pairs],
                "test": [x["stem"] for x in test_pairs],
            },
            f,
            indent=2,
            ensure_ascii=False
        )

    print("\nSaved new split:", split_path)
    return train_pairs, val_pairs, test_pairs


train_pairs, val_pairs, test_pairs = build_or_load_split(all_pairs, EXP_DIR)

print("\nSplit:")
print("Train:", len(train_pairs))
print("Val:", len(val_pairs))
print("Test:", len(test_pairs))


# ============================================================
# Dataset
# ============================================================

class CleanBorder128ToColor512Dataset(Dataset):
    def __init__(self, pairs, split_name: str):
        self.pairs = list(pairs)
        self.split_name = split_name

    def __len__(self):
        return len(self.pairs)

    def __getitem__(self, idx):
        item = self.pairs[idx]

        border_img = load_border_image_as_line_pil(
            item["border_path"],
            out_size=CONFIG["border_input_size"],
        )

        rgb_img, alpha_img = create_rgb_and_alpha_from_color_image(
            item["color_path"],
            out_size=CONFIG["color_output_size"],
            white_threshold=CONFIG["white_bg_threshold"],
        )

        border_tensor = pil_gray_mask_to_tensor(border_img)
        rgb_tensor = pil_rgb_to_tensor(rgb_img)
        alpha_tensor = pil_gray_mask_to_tensor(alpha_img)

        meta = {
            "name": item["name"],
            "stem": item["stem"],
            "split": self.split_name,
            "border_path": str(item["border_path"]),
            "color_path": str(item["color_path"]),
        }

        return border_tensor, rgb_tensor, alpha_tensor, meta


train_dataset = CleanBorder128ToColor512Dataset(train_pairs, split_name="train")
val_dataset = CleanBorder128ToColor512Dataset(val_pairs, split_name="val")
test_dataset = CleanBorder128ToColor512Dataset(test_pairs, split_name="test")

train_loader = DataLoader(
    train_dataset,
    batch_size=CONFIG["batch_size"],
    shuffle=True,
    num_workers=CONFIG["num_workers"],
    pin_memory=PIN_MEMORY,
    drop_last=False,
)

val_loader = DataLoader(
    val_dataset,
    batch_size=CONFIG["batch_size"],
    shuffle=False,
    num_workers=CONFIG["num_workers"],
    pin_memory=PIN_MEMORY,
    drop_last=False,
)

test_loader = DataLoader(
    test_dataset,
    batch_size=CONFIG["batch_size"],
    shuffle=False,
    num_workers=CONFIG["num_workers"],
    pin_memory=PIN_MEMORY,
    drop_last=False,
)

print("\nDataset size:")
print("Train:", len(train_dataset))
print("Val:", len(val_dataset))
print("Test:", len(test_dataset))


# ============================================================
# Dataset visual check
# ============================================================

def show_dataset_samples(dataset, num_samples=6, seed=123, save_path=None):
    rng = np.random.default_rng(seed)
    idxs = rng.choice(len(dataset), size=min(num_samples, len(dataset)), replace=False)

    fig, axes = plt.subplots(len(idxs), 3, figsize=(12, 4 * len(idxs)))

    if len(idxs) == 1:
        axes = np.expand_dims(axes, axis=0)

    for row, idx in enumerate(idxs):
        border, rgb, alpha, meta = dataset[int(idx)]

        axes[row, 0].imshow(tensor_to_gray_numpy(border), cmap="gray", vmin=0, vmax=1)
        axes[row, 0].set_title(f"Input border 128\n{meta['name']}")
        axes[row, 0].axis("off")

        axes[row, 1].imshow(tensor_to_rgb_numpy(rgb))
        axes[row, 1].set_title("Target RGB 512")
        axes[row, 1].axis("off")

        axes[row, 2].imshow(tensor_to_gray_numpy(alpha), cmap="gray", vmin=0, vmax=1)
        axes[row, 2].set_title("Target Alpha 512")
        axes[row, 2].axis("off")

    plt.tight_layout()

    if save_path is not None:
        plt.savefig(save_path, dpi=150, bbox_inches="tight")
        print("Saved:", save_path)

    plt.show()


show_dataset_samples(
    train_dataset,
    num_samples=6,
    seed=123,
    save_path=SAMPLE_DIR / "dataset_debug_128to512_clean.png"
)


# ============================================================
# Model: 128 -> 512
# ============================================================

class DoubleConv(nn.Module):
    def __init__(self, in_channels, out_channels):
        super().__init__()

        self.net = nn.Sequential(
            nn.Conv2d(in_channels, out_channels, 3, padding=1, bias=False),
            nn.BatchNorm2d(out_channels),
            nn.ReLU(inplace=True),

            nn.Conv2d(out_channels, out_channels, 3, padding=1, bias=False),
            nn.BatchNorm2d(out_channels),
            nn.ReLU(inplace=True),
        )

    def forward(self, x):
        return self.net(x)


class UpBlockNoSkip(nn.Module):
    """
    Decoder-only upsample block.
    Used after returning to 128px to reach 256 and 512.
    """
    def __init__(self, channels):
        super().__init__()
        self.up = nn.ConvTranspose2d(channels, channels, kernel_size=2, stride=2)
        self.conv = DoubleConv(channels, channels)

    def forward(self, x):
        x = self.up(x)
        x = self.conv(x)
        return x


class UNetRGBA128To512(nn.Module):
    """
    Input:
      [B, 1, 128, 128]

    Output:
      [B, 4, 512, 512]

    Structure:
      encoder:
        128 -> 64 -> 32 -> 16

      decoder with skips:
        16 -> 32 -> 64 -> 128

      extra decoder:
        128 -> 256 -> 512
    """
    def __init__(self, in_channels=1, out_channels=4, base_channels=24):
        super().__init__()

        c1 = base_channels
        c2 = base_channels * 2
        c3 = base_channels * 4
        c4 = base_channels * 8

        self.enc1 = DoubleConv(in_channels, c1)      # 128
        self.pool1 = nn.MaxPool2d(2)

        self.enc2 = DoubleConv(c1, c2)               # 64
        self.pool2 = nn.MaxPool2d(2)

        self.enc3 = DoubleConv(c2, c3)               # 32
        self.pool3 = nn.MaxPool2d(2)

        self.bottleneck = DoubleConv(c3, c4)         # 16

        self.up3 = nn.ConvTranspose2d(c4, c3, kernel_size=2, stride=2)  # 32
        self.dec3 = DoubleConv(c3 + c3, c3)

        self.up2 = nn.ConvTranspose2d(c3, c2, kernel_size=2, stride=2)  # 64
        self.dec2 = DoubleConv(c2 + c2, c2)

        self.up1 = nn.ConvTranspose2d(c2, c1, kernel_size=2, stride=2)  # 128
        self.dec1 = DoubleConv(c1 + c1, c1)

        # Additional decoder side: 128 -> 256 -> 512
        self.up0 = UpBlockNoSkip(c1)   # 256
        self.up_minus1 = UpBlockNoSkip(c1)  # 512

        self.out_conv = nn.Conv2d(c1, out_channels, kernel_size=1)

    def forward(self, x):
        e1 = self.enc1(x)
        e2 = self.enc2(self.pool1(e1))
        e3 = self.enc3(self.pool2(e2))

        b = self.bottleneck(self.pool3(e3))

        d3 = self.up3(b)
        d3 = torch.cat([d3, e3], dim=1)
        d3 = self.dec3(d3)

        d2 = self.up2(d3)
        d2 = torch.cat([d2, e2], dim=1)
        d2 = self.dec2(d2)

        d1 = self.up1(d2)
        d1 = torch.cat([d1, e1], dim=1)
        d1 = self.dec1(d1)

        d0 = self.up0(d1)          # 256
        d_minus1 = self.up_minus1(d0)  # 512

        return self.out_conv(d_minus1)


model = UNetRGBA128To512(
    in_channels=CONFIG["input_channels"],
    out_channels=CONFIG["output_channels"],
    base_channels=CONFIG["base_channels"],
).to(DEVICE)

print("\nModel:", model.__class__.__name__)
print("Trainable params:", sum(p.numel() for p in model.parameters() if p.requires_grad))


# ============================================================
# Loss
# ============================================================

def dice_loss_from_logits(logits, targets, eps=1e-6):
    probs = torch.sigmoid(logits)

    probs = probs.view(probs.size(0), -1)
    targets = targets.view(targets.size(0), -1)

    intersection = (probs * targets).sum(dim=1)
    denominator = probs.sum(dim=1) + targets.sum(dim=1)

    dice = (2.0 * intersection + eps) / (denominator + eps)
    return 1.0 - dice.mean()


def rgba_colorization_loss(output, rgb_target, alpha_target, eps=1e-6):
    """
    output:
      [B,4,512,512]
      output[:,0:3] = RGB logits
      output[:,3:4] = alpha logits
    """
    rgb_logit = output[:, 0:3, :, :]
    alpha_logit = output[:, 3:4, :, :]

    rgb_pred = torch.sigmoid(rgb_logit)

    # RGB loss only inside alpha target
    mask = alpha_target
    rgb_l1 = torch.abs(rgb_pred - rgb_target)
    rgb_inside_loss = (rgb_l1 * mask).sum() / (mask.sum() * 3.0 + eps)

    # Alpha loss on all pixels
    alpha_bce = F.binary_cross_entropy_with_logits(alpha_logit, alpha_target)
    alpha_dice = dice_loss_from_logits(alpha_logit, alpha_target, eps=eps)

    total = (
        CONFIG["rgb_loss_weight"] * rgb_inside_loss
        + CONFIG["alpha_bce_weight"] * alpha_bce
        + CONFIG["alpha_dice_weight"] * alpha_dice
    )

    bg_rgb_loss = torch.tensor(0.0, device=output.device)

    if CONFIG["background_rgb_weight"] > 0:
        bg_mask = 1.0 - alpha_target
        white = torch.ones_like(rgb_pred)

        bg_l1 = torch.abs(rgb_pred - white)
        bg_rgb_loss = (bg_l1 * bg_mask).sum() / (bg_mask.sum() * 3.0 + eps)

        total = total + CONFIG["background_rgb_weight"] * bg_rgb_loss

    return total, {
        "loss": total.detach(),
        "rgb_inside_loss": rgb_inside_loss.detach(),
        "alpha_bce": alpha_bce.detach(),
        "alpha_dice": alpha_dice.detach(),
        "bg_rgb_loss": bg_rgb_loss.detach(),
    }


# ============================================================
# Metrics
# ============================================================

@torch.no_grad()
def compute_batch_metrics(output, rgb_target, alpha_target, eps=1e-6):
    rgb_pred = torch.sigmoid(output[:, 0:3, :, :])
    alpha_prob = torch.sigmoid(output[:, 3:4, :, :])
    alpha_pred = (alpha_prob >= CONFIG["alpha_threshold"]).float()

    inter = (alpha_pred * alpha_target).sum(dim=(1, 2, 3))
    pred_sum = alpha_pred.sum(dim=(1, 2, 3))
    target_sum = alpha_target.sum(dim=(1, 2, 3))
    union = pred_sum + target_sum - inter

    alpha_dice = ((2.0 * inter + eps) / (pred_sum + target_sum + eps)).mean().item()
    alpha_iou = ((inter + eps) / (union + eps)).mean().item()

    mask = alpha_target
    rgb_mae_inside = (torch.abs(rgb_pred - rgb_target) * mask).sum() / (mask.sum() * 3.0 + eps)
    rgb_mae_inside = rgb_mae_inside.item()

    return {
        "alpha_dice": alpha_dice,
        "alpha_iou": alpha_iou,
        "rgb_mae_inside": rgb_mae_inside,
    }


# ============================================================
# Train / Eval functions
# ============================================================

def train_one_epoch(model, loader, optimizer, scaler):
    model.train()

    total = {
        "loss": 0.0,
        "rgb_inside_loss": 0.0,
        "alpha_bce": 0.0,
        "alpha_dice": 0.0,
        "bg_rgb_loss": 0.0,
        "alpha_dice_metric": 0.0,
        "alpha_iou_metric": 0.0,
        "rgb_mae_inside_metric": 0.0,
    }

    n_samples = 0

    pbar = tqdm(loader, desc="Train", leave=False)

    for border, rgb_target, alpha_target, meta in pbar:
        border = border.to(DEVICE, non_blocking=True)
        rgb_target = rgb_target.to(DEVICE, non_blocking=True)
        alpha_target = alpha_target.to(DEVICE, non_blocking=True)

        optimizer.zero_grad(set_to_none=True)

        with torch.amp.autocast(
            "cuda",
            enabled=(CONFIG["use_amp"] and DEVICE.type == "cuda"),
        ):
            output = model(border)
            loss, loss_dict = rgba_colorization_loss(output, rgb_target, alpha_target)

        scaler.scale(loss).backward()
        scaler.step(optimizer)
        scaler.update()

        metrics = compute_batch_metrics(output, rgb_target, alpha_target)

        bs = border.size(0)
        n_samples += bs

        total["loss"] += loss_dict["loss"].item() * bs
        total["rgb_inside_loss"] += loss_dict["rgb_inside_loss"].item() * bs
        total["alpha_bce"] += loss_dict["alpha_bce"].item() * bs
        total["alpha_dice"] += loss_dict["alpha_dice"].item() * bs
        total["bg_rgb_loss"] += loss_dict["bg_rgb_loss"].item() * bs

        total["alpha_dice_metric"] += metrics["alpha_dice"] * bs
        total["alpha_iou_metric"] += metrics["alpha_iou"] * bs
        total["rgb_mae_inside_metric"] += metrics["rgb_mae_inside"] * bs

        pbar.set_postfix({
            "loss": f"{loss_dict['loss'].item():.4f}",
            "rgb": f"{loss_dict['rgb_inside_loss'].item():.4f}",
            "a_bce": f"{loss_dict['alpha_bce'].item():.4f}",
            "a_dice": f"{loss_dict['alpha_dice'].item():.4f}",
        })

    for k in total:
        total[k] /= max(n_samples, 1)

    return total


@torch.no_grad()
def evaluate(model, loader):
    model.eval()

    total = {
        "loss": 0.0,
        "rgb_inside_loss": 0.0,
        "alpha_bce": 0.0,
        "alpha_dice": 0.0,
        "bg_rgb_loss": 0.0,
        "alpha_dice_metric": 0.0,
        "alpha_iou_metric": 0.0,
        "rgb_mae_inside_metric": 0.0,
    }

    n_samples = 0

    for border, rgb_target, alpha_target, meta in tqdm(loader, desc="Eval", leave=False):
        border = border.to(DEVICE, non_blocking=True)
        rgb_target = rgb_target.to(DEVICE, non_blocking=True)
        alpha_target = alpha_target.to(DEVICE, non_blocking=True)

        output = model(border)
        loss, loss_dict = rgba_colorization_loss(output, rgb_target, alpha_target)
        metrics = compute_batch_metrics(output, rgb_target, alpha_target)

        bs = border.size(0)
        n_samples += bs

        total["loss"] += loss_dict["loss"].item() * bs
        total["rgb_inside_loss"] += loss_dict["rgb_inside_loss"].item() * bs
        total["alpha_bce"] += loss_dict["alpha_bce"].item() * bs
        total["alpha_dice"] += loss_dict["alpha_dice"].item() * bs
        total["bg_rgb_loss"] += loss_dict["bg_rgb_loss"].item() * bs

        total["alpha_dice_metric"] += metrics["alpha_dice"] * bs
        total["alpha_iou_metric"] += metrics["alpha_iou"] * bs
        total["rgb_mae_inside_metric"] += metrics["rgb_mae_inside"] * bs

    for k in total:
        total[k] /= max(n_samples, 1)

    return total


# ============================================================
# Sample saving
# ============================================================

@torch.no_grad()
def save_validation_samples(
    model,
    dataset,
    epoch,
    save_dir,
    num_samples=6,
    seed=123,
):
    model.eval()

    if len(dataset) == 0:
        return None

    rng = np.random.default_rng(seed + epoch)
    idxs = rng.choice(len(dataset), size=min(num_samples, len(dataset)), replace=False)

    fig, axes = plt.subplots(len(idxs), 6, figsize=(22, 3.5 * len(idxs)))

    if len(idxs) == 1:
        axes = np.expand_dims(axes, axis=0)

    for row, idx in enumerate(idxs):
        border, rgb_target, alpha_target, meta = dataset[int(idx)]

        x = border.unsqueeze(0).to(DEVICE)
        output = model(x)

        rgb_pred = torch.sigmoid(output[:, 0:3])[0].cpu()
        alpha_pred = torch.sigmoid(output[:, 3:4])[0].cpu()
        alpha_bin = (alpha_pred >= CONFIG["alpha_threshold"]).float()

        border_np = tensor_to_gray_numpy(border)
        rgb_target_np = tensor_to_rgb_numpy(rgb_target)
        alpha_target_np = tensor_to_gray_numpy(alpha_target)

        rgb_pred_np = tensor_to_rgb_numpy(rgb_pred)
        alpha_pred_np = tensor_to_gray_numpy(alpha_pred)
        composite_np = alpha_composite_on_checker(
            rgb_pred_np,
            tensor_to_gray_numpy(alpha_bin),
        )

        axes[row, 0].imshow(border_np, cmap="gray", vmin=0, vmax=1)
        axes[row, 0].set_title(f"Input border 128\n{meta['name']}")
        axes[row, 0].axis("off")

        axes[row, 1].imshow(rgb_target_np)
        axes[row, 1].set_title("GT RGB 512")
        axes[row, 1].axis("off")

        axes[row, 2].imshow(alpha_target_np, cmap="gray", vmin=0, vmax=1)
        axes[row, 2].set_title("GT Alpha 512")
        axes[row, 2].axis("off")

        axes[row, 3].imshow(rgb_pred_np)
        axes[row, 3].set_title("Pred RGB 512")
        axes[row, 3].axis("off")

        axes[row, 4].imshow(alpha_pred_np, cmap="gray", vmin=0, vmax=1)
        axes[row, 4].set_title("Pred Alpha 512")
        axes[row, 4].axis("off")

        axes[row, 5].imshow(composite_np)
        axes[row, 5].set_title("Pred RGBA checker")
        axes[row, 5].axis("off")

    plt.tight_layout()

    save_path = Path(save_dir) / f"epoch_{epoch:03d}.png"
    plt.savefig(save_path, dpi=150, bbox_inches="tight")
    plt.close()

    return save_path


# ============================================================
# Optimizer / Scheduler / AMP
# ============================================================

optimizer = torch.optim.AdamW(
    model.parameters(),
    lr=CONFIG["learning_rate"],
    weight_decay=CONFIG["weight_decay"],
)

scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
    optimizer,
    mode="min",
    factor=0.5,
    patience=5,
)

scaler = torch.amp.GradScaler(
    "cuda",
    enabled=(CONFIG["use_amp"] and DEVICE.type == "cuda"),
)

print("\nPreparation done.")
print("Ready for main training loop.")
print("Experiment dir:", EXP_DIR)


# ============================================================
# Main training loop
# 128x128 input -> 512x512 RGBA output
# ============================================================

best_val_loss = float("inf")
best_epoch = -1
patience_counter = 0

log_path = LOG_DIR / "train_log.csv"

with open(log_path, "w", encoding="utf-8") as f:
    f.write(
        "epoch,"
        "train_loss,train_rgb_inside_loss,train_alpha_bce,train_alpha_dice,"
        "train_alpha_dice_metric,train_alpha_iou_metric,train_rgb_mae_inside_metric,"
        "val_loss,val_rgb_inside_loss,val_alpha_bce,val_alpha_dice,"
        "val_alpha_dice_metric,val_alpha_iou_metric,val_rgb_mae_inside_metric,"
        "lr\n"
    )

for epoch in range(1, CONFIG["epochs"] + 1):
    print(f"\nEpoch {epoch}/{CONFIG['epochs']}")

    train_metrics = train_one_epoch(model, train_loader, optimizer, scaler)
    val_metrics = evaluate(model, val_loader)

    scheduler.step(val_metrics["loss"])
    current_lr = optimizer.param_groups[0]["lr"]

    print(
        f"Train loss: {train_metrics['loss']:.5f} | "
        f"Train RGB: {train_metrics['rgb_inside_loss']:.5f} | "
        f"Train Alpha BCE: {train_metrics['alpha_bce']:.5f} | "
        f"Train Alpha DiceLoss: {train_metrics['alpha_dice']:.5f} | "
        f"Train Alpha Dice: {train_metrics['alpha_dice_metric']:.5f} | "
        f"Train Alpha IoU: {train_metrics['alpha_iou_metric']:.5f} | "
        f"Train RGB MAE(in): {train_metrics['rgb_mae_inside_metric']:.5f}"
    )

    print(
        f"Val loss: {val_metrics['loss']:.5f} | "
        f"Val RGB: {val_metrics['rgb_inside_loss']:.5f} | "
        f"Val Alpha BCE: {val_metrics['alpha_bce']:.5f} | "
        f"Val Alpha DiceLoss: {val_metrics['alpha_dice']:.5f} | "
        f"Val Alpha Dice: {val_metrics['alpha_dice_metric']:.5f} | "
        f"Val Alpha IoU: {val_metrics['alpha_iou_metric']:.5f} | "
        f"Val RGB MAE(in): {val_metrics['rgb_mae_inside_metric']:.5f} | "
        f"LR: {current_lr:.6f}"
    )

    with open(log_path, "a", encoding="utf-8") as f:
        f.write(
            f"{epoch},"
            f"{train_metrics['loss']:.8f},{train_metrics['rgb_inside_loss']:.8f},{train_metrics['alpha_bce']:.8f},{train_metrics['alpha_dice']:.8f},"
            f"{train_metrics['alpha_dice_metric']:.8f},{train_metrics['alpha_iou_metric']:.8f},{train_metrics['rgb_mae_inside_metric']:.8f},"
            f"{val_metrics['loss']:.8f},{val_metrics['rgb_inside_loss']:.8f},{val_metrics['alpha_bce']:.8f},{val_metrics['alpha_dice']:.8f},"
            f"{val_metrics['alpha_dice_metric']:.8f},{val_metrics['alpha_iou_metric']:.8f},{val_metrics['rgb_mae_inside_metric']:.8f},"
            f"{current_lr:.10f}\n"
        )

    sample_path = save_validation_samples(
        model=model,
        dataset=val_dataset,
        epoch=epoch,
        save_dir=SAMPLE_DIR,
        num_samples=6,
        seed=123,
    )
    print("Saved sample:", sample_path)

    last_checkpoint = {
        "epoch": epoch,
        "model_state_dict": model.state_dict(),
        "optimizer_state_dict": optimizer.state_dict(),
        "scheduler_state_dict": scheduler.state_dict(),
        "scaler_state_dict": scaler.state_dict(),
        "train_metrics": train_metrics,
        "val_metrics": val_metrics,
        "config": CONFIG,
    }

    torch.save(last_checkpoint, CHECKPOINT_DIR / "last_model.pt")

    if val_metrics["loss"] < best_val_loss:
        best_val_loss = val_metrics["loss"]
        best_epoch = epoch
        patience_counter = 0

        best_checkpoint = {
            "epoch": epoch,
            "model_state_dict": model.state_dict(),
            "optimizer_state_dict": optimizer.state_dict(),
            "scheduler_state_dict": scheduler.state_dict(),
            "scaler_state_dict": scaler.state_dict(),
            "train_metrics": train_metrics,
            "val_metrics": val_metrics,
            "config": CONFIG,
        }

        torch.save(best_checkpoint, CHECKPOINT_DIR / "best_model.pt")
        print(f"Best model updated. best_val_loss={best_val_loss:.5f}")

    else:
        patience_counter += 1
        print(f"No improvement. patience={patience_counter}/{CONFIG['early_stopping_patience']}")

    if patience_counter >= CONFIG["early_stopping_patience"]:
        print("Early stopping.")
        break

print(f"\nTraining finished. Best epoch: {best_epoch}, Best val loss: {best_val_loss:.5f}")


# ============================================================
# Load best model and evaluate on test set
# ============================================================

best_model_path = CHECKPOINT_DIR / "best_model.pt"

if not best_model_path.exists():
    raise FileNotFoundError(f"Best model not found: {best_model_path}")

checkpoint = torch.load(best_model_path, map_location=DEVICE)

model.load_state_dict(checkpoint["model_state_dict"])
model.to(DEVICE)
model.eval()

test_metrics = evaluate(model, test_loader)

print("\nTest metrics:")
for k, v in test_metrics.items():
    print(f"{k}: {v:.6f}")

with open(EXP_DIR / "test_metrics.json", "w", encoding="utf-8") as f:
    json.dump(test_metrics, f, indent=2, ensure_ascii=False)

test_sample_path = save_validation_samples(
    model=model,
    dataset=test_dataset,
    epoch=999,
    save_dir=SAMPLE_DIR,
    num_samples=6,
    seed=999,
)

print("Saved test sample:", test_sample_path)
print("Best model path:", best_model_path)
print("Log path:", log_path)