# -*- coding: utf-8 -*-
"""judge.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xXYND4TsJod4qfJ0cmzsEp4urZCq5bFU
"""

from google.colab import drive

drive.mount("/content/drive")

# ============================================================
# Quick, Draw! 7 Fruit Classifier
#
# Classes:
#   apple / banana / grapes / strawberry / pineapple / watermelon / pear
#
# Input:
#   256x256x1
#   background = 0
#   stroke     = 1
#
# Output:
#   sigmoid scores:
#   [
#     apple,
#     banana,
#     grapes,
#     strawberry,
#     pineapple,
#     watermelon,
#     pear
#   ]
#
# Decision:
#   if max(score) < threshold:
#       label = "none"
#   else:
#       label = argmax(score)
#
# Google Drive save root:
#   /content/drive/MyDrive/judge_ff
# ============================================================


# ============================================================
# 0. Install / Imports
# ============================================================

!pip -q install ndjson tqdm

import os
import json
import random
import math
import urllib.parse
import urllib.request
import urllib.error
import shutil
from pathlib import Path
from datetime import datetime

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from PIL import Image, ImageDraw

from tqdm.auto import tqdm

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

print("TensorFlow:", tf.__version__)
print("GPU:", tf.config.list_physical_devices("GPU"))


# ============================================================
# 1. Mount Google Drive
# ============================================================

from google.colab import drive

drive.mount("/content/drive")

DRIVE_ROOT_DIR = Path("/content/drive/MyDrive/judge_ff")
DRIVE_ROOT_DIR.mkdir(parents=True, exist_ok=True)

# 学習完了後の最終成果物保存先
DRIVE_LATEST_DIR = DRIVE_ROOT_DIR / "latest_7fruit_256"
DRIVE_LATEST_MODEL_DIR = DRIVE_LATEST_DIR / "fruit7_quickdraw_model_256"

# 学習途中のcheckpoint保存先
DRIVE_CHECKPOINT_DIR = DRIVE_ROOT_DIR / "latest_7fruit_256_checkpoints"

DRIVE_LATEST_DIR.mkdir(parents=True, exist_ok=True)
DRIVE_LATEST_MODEL_DIR.mkdir(parents=True, exist_ok=True)
DRIVE_CHECKPOINT_DIR.mkdir(parents=True, exist_ok=True)

print("Google Drive root:", DRIVE_ROOT_DIR)
print("Google Drive latest dir:", DRIVE_LATEST_DIR)
print("Google Drive checkpoint dir:", DRIVE_CHECKPOINT_DIR)


# ============================================================
# 2. Config
# ============================================================

SEED = 42
random.seed(SEED)
np.random.seed(SEED)
tf.random.set_seed(SEED)

IMG_SIZE = 256
CANVAS_SIZE = 256
DEFAULT_LINE_WIDTH = 2

CLASS_NAMES = [
    "apple",
    "banana",
    "grapes",
    "strawberry",
    "pineapple",
    "watermelon",
    "pear",
]

NUM_CLASSES = len(CLASS_NAMES)
CLASS_TO_INDEX = {name: i for i, name in enumerate(CLASS_NAMES)}

NEGATIVE_CLASSES = [
    "cat", "dog", "car", "bicycle", "house", "chair", "tree", "flower",
    "star", "cloud", "fish", "bird", "clock", "face", "hand", "cup",
    "book", "airplane", "umbrella", "shoe", "hat", "key", "bed", "door",
    "circle", "square", "triangle", "line", "moon", "sun",
    "cookie", "cake", "pizza", "sandwich", "hamburger",
    "baseball", "basketball", "soccer ball",
    "eye", "mouth", "nose", "ear",
]

SAMPLES_PER_POSITIVE_CLASS = 12000
SAMPLES_PER_NEGATIVE_CLASS = 800

NUM_BLANK_NEGATIVES = 1500
NUM_RANDOM_STROKE_NEGATIVES = 3000

TRAIN_RATIO = 0.80
VAL_RATIO = 0.10
TEST_RATIO = 0.10

BATCH_SIZE = 32
EPOCHS = 30

THRESHOLD = 0.60

DATA_DIR = Path("/content/quickdraw_data_7fruit_256")
NDJSON_DIR = DATA_DIR / "ndjson"
TFRECORD_DIR = DATA_DIR / "tfrecords"
MODEL_DIR = Path("/content/fruit7_quickdraw_model_256")

NDJSON_DIR.mkdir(parents=True, exist_ok=True)
TFRECORD_DIR.mkdir(parents=True, exist_ok=True)
MODEL_DIR.mkdir(parents=True, exist_ok=True)

BASE_URL = "https://storage.googleapis.com/quickdraw_dataset/full/simplified"

# すでにTFRecordを作成済みで、データ作成をスキップしたい場合は False にする。
REBUILD_TFRECORDS = False

if REBUILD_TFRECORDS and TFRECORD_DIR.exists():
    shutil.rmtree(TFRECORD_DIR)
    TFRECORD_DIR.mkdir(parents=True, exist_ok=True)
    print("Cleared old TFRecord cache:", TFRECORD_DIR)


# ============================================================
# 3. Download Quick, Draw! ndjson files
# ============================================================

def category_to_url(category: str) -> str:
    encoded = urllib.parse.quote(category, safe="")
    return f"{BASE_URL}/{encoded}.ndjson"


def safe_filename(category: str) -> str:
    return category.replace(" ", "_")


def download_category(category: str, out_dir: Path = NDJSON_DIR) -> Path | None:
    out_path = out_dir / f"{safe_filename(category)}.ndjson"

    if out_path.exists() and out_path.stat().st_size > 0:
        print(f"Already exists: {out_path}")
        return out_path

    url = category_to_url(category)
    print(f"Downloading {category}: {url}")

    try:
        urllib.request.urlretrieve(url, out_path)

    except urllib.error.HTTPError as e:
        if out_path.exists():
            out_path.unlink()

        if e.code == 404:
            print(f"WARNING: Category not found, skipped: {category}")
            return None

        raise RuntimeError(f"Failed to download {category} from {url}") from e

    except Exception as e:
        if out_path.exists():
            out_path.unlink()
        raise RuntimeError(f"Failed to download {category} from {url}") from e

    return out_path


all_categories = CLASS_NAMES + NEGATIVE_CLASSES

available_categories = []

for cat in all_categories:
    path = download_category(cat)
    if path is not None:
        available_categories.append(cat)

CLASS_NAMES = [cat for cat in CLASS_NAMES if cat in available_categories]
NEGATIVE_CLASSES = [cat for cat in NEGATIVE_CLASSES if cat in available_categories]

NUM_CLASSES = len(CLASS_NAMES)
CLASS_TO_INDEX = {name: i for i, name in enumerate(CLASS_NAMES)}

print("Available fruit classes:", CLASS_NAMES)
print("Num fruit classes:", NUM_CLASSES)
print("Available negative classes:", NEGATIVE_CLASSES)
print("Num negative classes:", len(NEGATIVE_CLASSES))


# ============================================================
# 4. Rasterization utilities
# ============================================================

def draw_strokes_to_image(
    drawing,
    img_size: int = IMG_SIZE,
    canvas_size: int = CANVAS_SIZE,
    line_width: int = DEFAULT_LINE_WIDTH,
    padding_ratio: float = 0.10,
    augment: bool = False,
):
    """
    Quick, Draw! のストロークデータを uint8 画像に変換する。

    output:
      shape = (IMG_SIZE, IMG_SIZE, 1)
      dtype = uint8
      background = 0
      stroke = 1
    """

    img = Image.new("L", (canvas_size, canvas_size), color=255)
    draw = ImageDraw.Draw(img)

    if augment:
        lw = random.choice([1, 2, 2, 3, 4])
    else:
        lw = line_width

    for stroke in drawing:
        xs, ys = stroke[0], stroke[1]
        points = list(zip(xs, ys))

        if len(points) == 1:
            x, y = points[0]
            r = max(1, lw // 2)
            draw.ellipse((x - r, y - r, x + r, y + r), fill=0)

        elif len(points) >= 2:
            draw.line(points, fill=0, width=lw, joint="curve")

    arr = np.array(img)
    black_pixels = np.where(arr < 255)

    if len(black_pixels[0]) == 0:
        img = Image.new("L", (img_size, img_size), color=255)

    else:
        y_min, y_max = black_pixels[0].min(), black_pixels[0].max()
        x_min, x_max = black_pixels[1].min(), black_pixels[1].max()

        crop = img.crop((x_min, y_min, x_max + 1, y_max + 1))

        w, h = crop.size
        side = max(w, h)
        padding = int(side * padding_ratio)
        new_side = max(1, side + 2 * padding)

        square = Image.new("L", (new_side, new_side), color=255)

        paste_x = (new_side - w) // 2
        paste_y = (new_side - h) // 2
        square.paste(crop, (paste_x, paste_y))

        img = square.resize((img_size, img_size), Image.Resampling.LANCZOS)

    if augment:
        angle = random.uniform(-10, 10)
        img = img.rotate(angle, fillcolor=255)

        max_shift = max(4, img_size // 32)
        tx = random.randint(-max_shift, max_shift)
        ty = random.randint(-max_shift, max_shift)

        shifted = Image.new("L", (img_size, img_size), color=255)
        shifted.paste(img, (tx, ty))
        img = shifted

    arr = np.array(img).astype(np.uint8)
    arr = (arr < 200).astype(np.uint8)

    return arr[..., None]


def make_blank_image(img_size: int = IMG_SIZE):
    return np.zeros((img_size, img_size, 1), dtype=np.uint8)


def make_random_stroke_image(
    img_size: int = IMG_SIZE,
    canvas_size: int = CANVAS_SIZE,
):
    img = Image.new("L", (canvas_size, canvas_size), color=255)
    draw = ImageDraw.Draw(img)

    num_strokes = random.randint(1, 6)

    for _ in range(num_strokes):
        num_points = random.randint(2, 10)
        points = []

        x = random.randint(20, canvas_size - 20)
        y = random.randint(20, canvas_size - 20)

        for _ in range(num_points):
            x += random.randint(-60, 60)
            y += random.randint(-60, 60)

            x = max(0, min(canvas_size - 1, x))
            y = max(0, min(canvas_size - 1, y))

            points.append((x, y))

        draw.line(points, fill=0, width=random.choice([1, 2, 3, 4]))

    img = img.resize((img_size, img_size), Image.Resampling.LANCZOS)

    arr = np.array(img).astype(np.uint8)
    arr = (arr < 200).astype(np.uint8)

    return arr[..., None]


def show_samples(images, labels=None, n=16, title=None):
    plt.figure(figsize=(8, 8))

    for i in range(min(n, len(images))):
        plt.subplot(4, 4, i + 1)
        plt.imshow(images[i].squeeze(), cmap="gray")
        plt.axis("off")

        if labels is not None:
            plt.title(str(labels[i]), fontsize=8)

    if title:
        plt.suptitle(title)

    plt.tight_layout()
    plt.show()


# ============================================================
# 5. ndjson iterator
# ============================================================

def iter_ndjson_records(path: Path, max_records: int, recognized_only: bool = True):
    count = 0

    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            if count >= max_records:
                break

            try:
                obj = json.loads(line)
            except json.JSONDecodeError:
                continue

            if recognized_only and not obj.get("recognized", False):
                continue

            drawing = obj.get("drawing")
            if drawing is None:
                continue

            yield obj
            count += 1


# ============================================================
# 6. TFRecord serialization
# ============================================================

def bytes_feature(value: bytes):
    return tf.train.Feature(bytes_list=tf.train.BytesList(value=[value]))


def float_list_feature(values):
    return tf.train.Feature(float_list=tf.train.FloatList(value=values))


def int64_feature(value: int):
    return tf.train.Feature(int64_list=tf.train.Int64List(value=[value]))


def str_feature(value: str):
    return tf.train.Feature(bytes_list=tf.train.BytesList(value=[value.encode("utf-8")]))


def serialize_example(image_uint8, label_float32, target_name, category_name):
    feature = {
        "image_raw": bytes_feature(image_uint8.tobytes()),
        "label": float_list_feature(label_float32.astype(np.float32).tolist()),
        "target": str_feature(target_name),
        "category": str_feature(category_name),
        "height": int64_feature(IMG_SIZE),
        "width": int64_feature(IMG_SIZE),
        "channels": int64_feature(1),
    }

    example = tf.train.Example(features=tf.train.Features(feature=feature))
    return example.SerializeToString()


def split_name_for_random():
    r = random.random()

    if r < TRAIN_RATIO:
        return "train"
    elif r < TRAIN_RATIO + VAL_RATIO:
        return "val"
    else:
        return "test"


def build_tfrecords(force_rebuild: bool = False):
    train_path = TFRECORD_DIR / "train.tfrecord"
    val_path = TFRECORD_DIR / "val.tfrecord"
    test_path = TFRECORD_DIR / "test.tfrecord"
    meta_path = TFRECORD_DIR / "dataset_meta.csv"

    if (
        train_path.exists()
        and val_path.exists()
        and test_path.exists()
        and meta_path.exists()
        and not force_rebuild
    ):
        print("TFRecords already exist.")
        meta = pd.read_csv(meta_path)
        return train_path, val_path, test_path, meta

    for p in [train_path, val_path, test_path, meta_path]:
        if p.exists():
            p.unlink()

    writers = {
        "train": tf.io.TFRecordWriter(str(train_path)),
        "val": tf.io.TFRecordWriter(str(val_path)),
        "test": tf.io.TFRecordWriter(str(test_path)),
    }

    counts = {
        "train": 0,
        "val": 0,
        "test": 0,
    }

    meta_rows = []

    try:
        # Positive classes
        for cat in CLASS_NAMES:
            path = NDJSON_DIR / f"{safe_filename(cat)}.ndjson"
            class_idx = CLASS_TO_INDEX[cat]

            label = np.zeros(NUM_CLASSES, dtype=np.float32)
            label[class_idx] = 1.0

            print(f"Writing positive class: {cat}")

            records = iter_ndjson_records(
                path,
                SAMPLES_PER_POSITIVE_CLASS,
                recognized_only=True
            )

            for obj in tqdm(records, total=SAMPLES_PER_POSITIVE_CLASS):
                image = draw_strokes_to_image(
                    obj["drawing"],
                    img_size=IMG_SIZE,
                    line_width=DEFAULT_LINE_WIDTH,
                    augment=False,
                )

                split = split_name_for_random()

                serialized = serialize_example(
                    image_uint8=image,
                    label_float32=label,
                    target_name=cat,
                    category_name=cat,
                )

                writers[split].write(serialized)
                counts[split] += 1

                meta_rows.append({
                    "split": split,
                    "category": cat,
                    "target": cat,
                    "is_negative": False,
                    "key_id": obj.get("key_id", ""),
                    "countrycode": obj.get("countrycode", ""),
                })

        # Negative classes
        print("Writing negative classes...")

        negative_label = np.zeros(NUM_CLASSES, dtype=np.float32)

        for cat in NEGATIVE_CLASSES:
            path = NDJSON_DIR / f"{safe_filename(cat)}.ndjson"

            if not path.exists():
                print(f"WARNING: missing file, skipped: {path}")
                continue

            records = iter_ndjson_records(
                path,
                SAMPLES_PER_NEGATIVE_CLASS,
                recognized_only=True
            )

            for obj in tqdm(records, total=SAMPLES_PER_NEGATIVE_CLASS, desc=f"negative: {cat}"):
                image = draw_strokes_to_image(
                    obj["drawing"],
                    img_size=IMG_SIZE,
                    line_width=DEFAULT_LINE_WIDTH,
                    augment=False,
                )

                split = split_name_for_random()

                serialized = serialize_example(
                    image_uint8=image,
                    label_float32=negative_label,
                    target_name="none",
                    category_name=cat,
                )

                writers[split].write(serialized)
                counts[split] += 1

                meta_rows.append({
                    "split": split,
                    "category": cat,
                    "target": "none",
                    "is_negative": True,
                    "key_id": obj.get("key_id", ""),
                    "countrycode": obj.get("countrycode", ""),
                })

        # Blank negatives
        print("Writing blank negatives...")

        for _ in tqdm(range(NUM_BLANK_NEGATIVES)):
            image = make_blank_image(IMG_SIZE)
            split = split_name_for_random()

            serialized = serialize_example(
                image_uint8=image,
                label_float32=negative_label,
                target_name="none",
                category_name="__blank__",
            )

            writers[split].write(serialized)
            counts[split] += 1

            meta_rows.append({
                "split": split,
                "category": "__blank__",
                "target": "none",
                "is_negative": True,
                "key_id": "",
                "countrycode": "",
            })

        # Random stroke negatives
        print("Writing random stroke negatives...")

        for _ in tqdm(range(NUM_RANDOM_STROKE_NEGATIVES)):
            image = make_random_stroke_image(IMG_SIZE)
            split = split_name_for_random()

            serialized = serialize_example(
                image_uint8=image,
                label_float32=negative_label,
                target_name="none",
                category_name="__random_stroke__",
            )

            writers[split].write(serialized)
            counts[split] += 1

            meta_rows.append({
                "split": split,
                "category": "__random_stroke__",
                "target": "none",
                "is_negative": True,
                "key_id": "",
                "countrycode": "",
            })

    finally:
        for writer in writers.values():
            writer.close()

    meta = pd.DataFrame(meta_rows)
    meta.to_csv(meta_path, index=False)

    print("TFRecord counts:", counts)
    print("Saved TFRecords:")
    print(train_path)
    print(val_path)
    print(test_path)
    print(meta_path)

    return train_path, val_path, test_path, meta


train_tfrecord, val_tfrecord, test_tfrecord, meta = build_tfrecords(
    force_rebuild=REBUILD_TFRECORDS
)

display(meta.head())
display(meta["split"].value_counts())
display(meta["target"].value_counts())
display(meta["category"].value_counts().head(30))


# ============================================================
# 7. Visual check from TFRecord
# ============================================================

def parse_example(serialized):
    feature_description = {
        "image_raw": tf.io.FixedLenFeature([], tf.string),
        "label": tf.io.FixedLenFeature([NUM_CLASSES], tf.float32),
        "target": tf.io.FixedLenFeature([], tf.string),
        "category": tf.io.FixedLenFeature([], tf.string),
        "height": tf.io.FixedLenFeature([], tf.int64),
        "width": tf.io.FixedLenFeature([], tf.int64),
        "channels": tf.io.FixedLenFeature([], tf.int64),
    }

    example = tf.io.parse_single_example(serialized, feature_description)

    image = tf.io.decode_raw(example["image_raw"], tf.uint8)
    image = tf.reshape(image, [IMG_SIZE, IMG_SIZE, 1])
    image = tf.cast(image, tf.float32)

    label = example["label"]
    target = example["target"]
    category = example["category"]

    return image, label, target, category


def preview_tfrecord(tfrecord_path, n=16):
    ds = tf.data.TFRecordDataset(str(tfrecord_path))
    ds = ds.map(parse_example)
    ds = ds.take(n)

    images = []
    labels = []

    for image, label, target, category in ds:
        images.append(image.numpy())
        labels.append(target.numpy().decode("utf-8"))

    show_samples(images, labels, n=n, title="TFRecord preview")


preview_tfrecord(train_tfrecord, n=16)


# ============================================================
# 8. tf.data pipeline
# ============================================================

AUTOTUNE = tf.data.AUTOTUNE

def parse_for_training(serialized):
    feature_description = {
        "image_raw": tf.io.FixedLenFeature([], tf.string),
        "label": tf.io.FixedLenFeature([NUM_CLASSES], tf.float32),
    }

    example = tf.io.parse_single_example(serialized, feature_description)

    image = tf.io.decode_raw(example["image_raw"], tf.uint8)
    image = tf.reshape(image, [IMG_SIZE, IMG_SIZE, 1])
    image = tf.cast(image, tf.float32)

    label = example["label"]

    return image, label


def augment_image_tf(image, label):
    image = tf.cond(
        tf.random.uniform(()) < 0.5,
        lambda: tf.image.flip_left_right(image),
        lambda: image,
    )

    pad = 10

    image_padded = tf.pad(
        image,
        [[pad, pad], [pad, pad], [0, 0]],
        constant_values=0.0
    )

    image = tf.image.random_crop(
        image_padded,
        size=[IMG_SIZE, IMG_SIZE, 1]
    )

    keep_prob = tf.random.uniform((), 0.965, 1.0)

    mask = tf.cast(
        tf.random.uniform(tf.shape(image)) < keep_prob,
        tf.float32
    )

    image = image * mask
    image = tf.clip_by_value(image, 0.0, 1.0)

    return image, label


def make_dataset(tfrecord_path, training: bool, repeat: bool = False):
    ds = tf.data.TFRecordDataset(
        str(tfrecord_path),
        num_parallel_reads=AUTOTUNE
    )

    if training:
        ds = ds.shuffle(
            buffer_size=8192,
            seed=SEED,
            reshuffle_each_iteration=True
        )

    ds = ds.map(parse_for_training, num_parallel_calls=AUTOTUNE)

    if training:
        ds = ds.map(augment_image_tf, num_parallel_calls=AUTOTUNE)

    if repeat:
        ds = ds.repeat()

    ds = ds.batch(BATCH_SIZE, drop_remainder=False)
    ds = ds.prefetch(AUTOTUNE)

    return ds


train_ds = make_dataset(train_tfrecord, training=True, repeat=True)
val_ds = make_dataset(val_tfrecord, training=False, repeat=True)
test_ds = make_dataset(test_tfrecord, training=False, repeat=False)

train_count = int((meta["split"] == "train").sum())
val_count = int((meta["split"] == "val").sum())
test_count = int((meta["split"] == "test").sum())

steps_per_epoch = math.ceil(train_count / BATCH_SIZE)
validation_steps = math.ceil(val_count / BATCH_SIZE)
test_steps = math.ceil(test_count / BATCH_SIZE)

print("train_count:", train_count)
print("val_count:", val_count)
print("test_count:", test_count)
print("steps_per_epoch:", steps_per_epoch)
print("validation_steps:", validation_steps)
print("test_steps:", test_steps)


# ============================================================
# 9. Model definition
# ============================================================

def conv_block(x, filters, dropout=0.0):
    x = layers.SeparableConv2D(
        filters,
        kernel_size=3,
        padding="same",
        use_bias=False
    )(x)
    x = layers.BatchNormalization()(x)
    x = layers.ReLU()(x)

    x = layers.SeparableConv2D(
        filters,
        kernel_size=3,
        padding="same",
        use_bias=False
    )(x)
    x = layers.BatchNormalization()(x)
    x = layers.ReLU()(x)

    if dropout > 0:
        x = layers.Dropout(dropout)(x)

    return x


def build_model(img_size=IMG_SIZE, num_classes=NUM_CLASSES):
    inputs = keras.Input(shape=(img_size, img_size, 1), name="image")

    x = inputs

    # 256x256
    x = conv_block(x, 24, dropout=0.00)
    x = layers.MaxPooling2D(pool_size=2)(x)

    # 128x128
    x = conv_block(x, 48, dropout=0.05)
    x = layers.MaxPooling2D(pool_size=2)(x)

    # 64x64
    x = conv_block(x, 96, dropout=0.08)
    x = layers.MaxPooling2D(pool_size=2)(x)

    # 32x32
    x = conv_block(x, 128, dropout=0.10)
    x = layers.MaxPooling2D(pool_size=2)(x)

    # 16x16
    x = conv_block(x, 192, dropout=0.12)
    x = layers.MaxPooling2D(pool_size=2)(x)

    # 8x8
    x = conv_block(x, 256, dropout=0.15)

    x = layers.GlobalAveragePooling2D()(x)

    x = layers.Dense(128, activation="relu")(x)
    x = layers.Dropout(0.30)(x)

    x = layers.Dense(64, activation="relu")(x)
    x = layers.Dropout(0.20)(x)

    outputs = layers.Dense(
        num_classes,
        activation="sigmoid",
        name="fruit_scores"
    )(x)

    model = keras.Model(
        inputs=inputs,
        outputs=outputs,
        name="quickdraw_7fruit_256_sigmoid_cnn"
    )

    return model


model = build_model()
model.summary()


# ============================================================
# 10. Compile
# ============================================================

model.compile(
    optimizer=keras.optimizers.Adam(learning_rate=1e-3),
    loss=keras.losses.BinaryCrossentropy(),
    metrics=[
        keras.metrics.BinaryAccuracy(name="bin_acc", threshold=0.5),
        keras.metrics.AUC(name="auc", multi_label=True),
    ]
)


# ============================================================
# 11. Callbacks
# ============================================================

best_checkpoint_path = MODEL_DIR / "best_model.keras"
latest_checkpoint_path = MODEL_DIR / "latest_model.keras"
backup_dir = MODEL_DIR / "training_backup"
csv_log_path = MODEL_DIR / "training_log.csv"

drive_best_checkpoint_path = DRIVE_CHECKPOINT_DIR / "best_model.keras"
drive_latest_checkpoint_path = DRIVE_CHECKPOINT_DIR / "latest_model.keras"
drive_csv_log_path = DRIVE_CHECKPOINT_DIR / "training_log.csv"


class CopyCheckpointToDriveCallback(keras.callbacks.Callback):
    def __init__(
        self,
        local_latest_path,
        local_best_path,
        local_csv_log_path,
        drive_dir,
    ):
        super().__init__()
        self.local_latest_path = Path(local_latest_path)
        self.local_best_path = Path(local_best_path)
        self.local_csv_log_path = Path(local_csv_log_path)
        self.drive_dir = Path(drive_dir)
        self.drive_dir.mkdir(parents=True, exist_ok=True)

    def on_epoch_end(self, epoch, logs=None):
        epoch_num = epoch + 1

        if self.local_latest_path.exists():
            dst_latest = self.drive_dir / "latest_model.keras"
            dst_epoch = self.drive_dir / f"latest_model_epoch_{epoch_num:03d}.keras"

            shutil.copy2(self.local_latest_path, dst_latest)
            shutil.copy2(self.local_latest_path, dst_epoch)

            print(f"Copied latest checkpoint to Drive: {dst_latest}")

        if self.local_best_path.exists():
            dst_best = self.drive_dir / "best_model.keras"
            shutil.copy2(self.local_best_path, dst_best)

        if self.local_csv_log_path.exists():
            dst_log = self.drive_dir / "training_log.csv"
            shutil.copy2(self.local_csv_log_path, dst_log)


callbacks = [
    keras.callbacks.ModelCheckpoint(
        filepath=str(best_checkpoint_path),
        monitor="val_loss",
        save_best_only=True,
        save_weights_only=False,
        verbose=1,
    ),

    keras.callbacks.ModelCheckpoint(
        filepath=str(latest_checkpoint_path),
        save_best_only=False,
        save_weights_only=False,
        verbose=1,
    ),

    keras.callbacks.BackupAndRestore(
        backup_dir=str(backup_dir)
    ),

    keras.callbacks.CSVLogger(
        filename=str(csv_log_path),
        append=True
    ),

    CopyCheckpointToDriveCallback(
        local_latest_path=latest_checkpoint_path,
        local_best_path=best_checkpoint_path,
        local_csv_log_path=csv_log_path,
        drive_dir=DRIVE_CHECKPOINT_DIR,
    ),

    keras.callbacks.ReduceLROnPlateau(
        monitor="val_loss",
        factor=0.5,
        patience=3,
        min_lr=1e-5,
        verbose=1,
    ),

    keras.callbacks.EarlyStopping(
        monitor="val_loss",
        patience=7,
        restore_best_weights=True,
        verbose=1,
    ),
]


# ============================================================
# 12. Train
# ============================================================

history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=EPOCHS,
    steps_per_epoch=steps_per_epoch,
    validation_steps=validation_steps,
    callbacks=callbacks,
)


# ============================================================
# 13. Plot training curves
# ============================================================

hist = pd.DataFrame(history.history)

plt.figure(figsize=(8, 5))
plt.plot(hist["loss"], label="train_loss")
plt.plot(hist["val_loss"], label="val_loss")
plt.xlabel("epoch")
plt.ylabel("loss")
plt.legend()
plt.grid(True)
plt.show()

plt.figure(figsize=(8, 5))

if "auc" in hist.columns:
    plt.plot(hist["auc"], label="train_auc")

if "val_auc" in hist.columns:
    plt.plot(hist["val_auc"], label="val_auc")

plt.xlabel("epoch")
plt.ylabel("AUC")
plt.legend()
plt.grid(True)
plt.show()


# ============================================================
# 14. Evaluation utilities
# ============================================================

def scores_to_labels(scores, threshold=THRESHOLD):
    max_scores = np.max(scores, axis=1)
    argmaxes = np.argmax(scores, axis=1)

    labels = []

    for max_score, idx in zip(max_scores, argmaxes):
        if max_score < threshold:
            labels.append("none")
        else:
            labels.append(CLASS_NAMES[idx])

    return np.array(labels)


def y_to_true_labels(y):
    labels = []

    for row in y:
        if np.sum(row) == 0:
            labels.append("none")
        else:
            labels.append(CLASS_NAMES[int(np.argmax(row))])

    return np.array(labels)


def collect_predictions(model, ds):
    all_scores = []
    all_y = []

    for batch_x, batch_y in tqdm(ds, desc="Predicting"):
        scores = model.predict(batch_x, verbose=0)
        all_scores.append(scores)
        all_y.append(batch_y.numpy())

    all_scores = np.concatenate(all_scores, axis=0)
    all_y = np.concatenate(all_y, axis=0)

    return all_scores, all_y


def evaluate_threshold(model, ds, threshold=THRESHOLD):
    scores, y_true = collect_predictions(model, ds)

    pred_labels = scores_to_labels(scores, threshold=threshold)
    true_labels = y_to_true_labels(y_true)

    acc = np.mean(pred_labels == true_labels)

    labels = CLASS_NAMES + ["none"]

    cm = pd.DataFrame(
        0,
        index=[f"true_{x}" for x in labels],
        columns=[f"pred_{x}" for x in labels],
    )

    for t, p in zip(true_labels, pred_labels):
        cm.loc[f"true_{t}", f"pred_{p}"] += 1

    return acc, cm, scores, pred_labels, true_labels, y_true


# ============================================================
# 15. Test evaluation with several thresholds
# ============================================================

for th in [0.40, 0.50, 0.60, 0.70, 0.80]:
    acc, cm, _, _, _, _ = evaluate_threshold(
        model,
        test_ds,
        threshold=th
    )

    print(f"\nThreshold: {th:.2f}")
    print(f"Label accuracy: {acc:.4f}")
    display(cm)


acc, cm, test_scores, pred_labels, true_labels, y_true = evaluate_threshold(
    model,
    test_ds,
    threshold=THRESHOLD
)

print("Selected threshold:", THRESHOLD)
print("Test label accuracy:", acc)
display(cm)


# ============================================================
# 16. Single image inference function
# ============================================================

def classify_image_array(
    image_array,
    model,
    threshold: float = THRESHOLD,
    smoothing_prev=None,
    smoothing_alpha: float = 0.30,
):
    img = image_array.astype(np.float32)

    if img.ndim == 2:
        img = img[..., None]

    if img.shape != (IMG_SIZE, IMG_SIZE, 1):
        raise ValueError(
            f"Expected shape {(IMG_SIZE, IMG_SIZE, 1)}, got {img.shape}"
        )

    img = np.clip(img, 0.0, 1.0)

    scores = model.predict(img[None, ...], verbose=0)[0]

    if smoothing_prev is not None:
        scores = (1.0 - smoothing_alpha) * smoothing_prev + smoothing_alpha * scores

    max_score = float(np.max(scores))
    max_idx = int(np.argmax(scores))

    if max_score < threshold:
        label = "none"
    else:
        label = CLASS_NAMES[max_idx]

    return {
        "label": label,
        "max_score": max_score,
        "threshold": threshold,
        "scores": {
            CLASS_NAMES[i]: float(scores[i])
            for i in range(NUM_CLASSES)
        },
        "smoothed_scores": scores,
    }


# ============================================================
# 17. Latency benchmark
# ============================================================

def benchmark_latency(model, batch_size=1, num_warmup=20, num_runs=100):
    dummy = np.random.rand(
        batch_size,
        IMG_SIZE,
        IMG_SIZE,
        1
    ).astype(np.float32)

    for _ in range(num_warmup):
        _ = model.predict(dummy, verbose=0)

    times = []

    for _ in range(num_runs):
        start = tf.timestamp()
        _ = model.predict(dummy, verbose=0)
        end = tf.timestamp()

        times.append(float((end - start).numpy()) * 1000.0)

    times = np.array(times)

    return {
        "batch_size": batch_size,
        "p50_ms": float(np.percentile(times, 50)),
        "p90_ms": float(np.percentile(times, 90)),
        "p95_ms": float(np.percentile(times, 95)),
        "mean_ms": float(np.mean(times)),
    }


latency_result = benchmark_latency(model, batch_size=1)

print("Latency:")
print(latency_result)


# ============================================================
# 18. Save final Keras model
# ============================================================

final_keras_path = MODEL_DIR / "quickdraw_7fruit_256_sigmoid.keras"

model.save(final_keras_path)

print("Saved Keras model:", final_keras_path)


# ============================================================
# 19. Export SavedModel
# ============================================================

savedmodel_dir = MODEL_DIR / "saved_model"

if savedmodel_dir.exists():
    shutil.rmtree(savedmodel_dir)

model.export(savedmodel_dir)

print("SavedModel exported:", savedmodel_dir)


# ============================================================
# 20. Export TFLite float32
# ============================================================

tflite_float_path = MODEL_DIR / "quickdraw_7fruit_256_float32.tflite"

converter = tf.lite.TFLiteConverter.from_saved_model(str(savedmodel_dir))
tflite_model = converter.convert()

with open(tflite_float_path, "wb") as f:
    f.write(tflite_model)

print("Saved TFLite float32:", tflite_float_path)
print("Size MB:", os.path.getsize(tflite_float_path) / 1024 / 1024)


# ============================================================
# 21. Export TFLite dynamic range quantized
# ============================================================

tflite_dynamic_path = MODEL_DIR / "quickdraw_7fruit_256_dynamic_quant.tflite"

converter = tf.lite.TFLiteConverter.from_saved_model(str(savedmodel_dir))
converter.optimizations = [tf.lite.Optimize.DEFAULT]
tflite_dynamic_model = converter.convert()

with open(tflite_dynamic_path, "wb") as f:
    f.write(tflite_dynamic_model)

print("Saved TFLite dynamic quantized:", tflite_dynamic_path)
print("Size MB:", os.path.getsize(tflite_dynamic_path) / 1024 / 1024)


# ============================================================
# 22. Save config file
# ============================================================

config = {
    "input_size": IMG_SIZE,
    "input_channels": 1,
    "input_dtype_for_model": "float32",
    "input_value_meaning": {
        "0": "background",
        "1": "stroke"
    },
    "class_names": CLASS_NAMES,
    "num_classes": NUM_CLASSES,
    "output_activation": "sigmoid",
    "recommended_threshold": THRESHOLD,
    "line_width_px": DEFAULT_LINE_WIDTH,
    "preprocessing": {
        "canvas": "white background, black stroke",
        "crop": "crop bounding box of stroke pixels",
        "padding_ratio": 0.10,
        "resize": f"{IMG_SIZE}x{IMG_SIZE}",
        "binarize": "stroke pixels -> 1, background -> 0"
    },
    "decision_rule": "if max(score) < threshold, label is none; otherwise argmax class",
    "positive_classes": CLASS_NAMES,
    "negative_classes": NEGATIVE_CLASSES,
    "samples_per_positive_class": SAMPLES_PER_POSITIVE_CLASS,
    "samples_per_negative_class": SAMPLES_PER_NEGATIVE_CLASS,
    "num_blank_negatives": NUM_BLANK_NEGATIVES,
    "num_random_stroke_negatives": NUM_RANDOM_STROKE_NEGATIVES,
    "batch_size": BATCH_SIZE,
    "epochs": EPOCHS,
    "model_type": "SeparableConv2D CNN",
    "tfrecord_dir": str(TFRECORD_DIR),
}

config_path = MODEL_DIR / "model_config.json"

with open(config_path, "w", encoding="utf-8") as f:
    json.dump(config, f, ensure_ascii=False, indent=2)

print("Saved config:", config_path)


# ============================================================
# 23. Save dataset meta summary
# ============================================================

dataset_summary_path = MODEL_DIR / "dataset_summary.csv"
meta.to_csv(dataset_summary_path, index=False)

print("Saved dataset summary:", dataset_summary_path)


# ============================================================
# 24. Zip artifacts
# ============================================================

local_zip_path = Path("/content/fruit7_quickdraw_model_256.zip")

if local_zip_path.exists():
    local_zip_path.unlink()

!cd /content && zip -r fruit7_quickdraw_model_256.zip fruit7_quickdraw_model_256

print("Created zip:", local_zip_path)


# ============================================================
# 25. Copy final artifacts to Google Drive
# ============================================================

timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

drive_run_dir = DRIVE_ROOT_DIR / f"run_7fruit_256_{timestamp}"
drive_run_model_dir = drive_run_dir / "fruit7_quickdraw_model_256"

drive_run_dir.mkdir(parents=True, exist_ok=True)

# 履歴保存
if drive_run_model_dir.exists():
    shutil.rmtree(drive_run_model_dir)

shutil.copytree(
    MODEL_DIR,
    drive_run_model_dir,
    dirs_exist_ok=True
)

if local_zip_path.exists():
    shutil.copy2(
        local_zip_path,
        drive_run_dir / "fruit7_quickdraw_model_256.zip"
    )

# latest保存
if DRIVE_MODEL_DIR.exists():
    shutil.rmtree(DRIVE_MODEL_DIR)

DRIVE_MODEL_DIR.mkdir(parents=True, exist_ok=True)

shutil.copytree(
    MODEL_DIR,
    DRIVE_MODEL_DIR,
    dirs_exist_ok=True
)

if local_zip_path.exists():
    shutil.copy2(
        local_zip_path,
        DRIVE_LATEST_DIR / "fruit7_quickdraw_model_256.zip"
    )

# checkpointもlatest配下へコピー
if best_checkpoint_path.exists():
    shutil.copy2(best_checkpoint_path, DRIVE_MODEL_DIR / "best_model.keras")

if latest_checkpoint_path.exists():
    shutil.copy2(latest_checkpoint_path, DRIVE_MODEL_DIR / "latest_model.keras")

if csv_log_path.exists():
    shutil.copy2(csv_log_path, DRIVE_MODEL_DIR / "training_log.csv")

print("Saved artifacts to Google Drive:")
print("Run directory:", drive_run_dir)
print("Latest directory:", DRIVE_LATEST_DIR)
print("Latest model directory:", DRIVE_MODEL_DIR)
print("Checkpoint directory:", DRIVE_CHECKPOINT_DIR)


# ============================================================
# 26. Final summary
# ============================================================

print("Done.")
print("Artifacts:")
print("- Keras:", final_keras_path)
print("- Best checkpoint:", best_checkpoint_path)
print("- Latest checkpoint:", latest_checkpoint_path)
print("- SavedModel:", savedmodel_dir)
print("- TFLite float32:", tflite_float_path)
print("- TFLite dynamic quant:", tflite_dynamic_path)
print("- Config:", config_path)
print("- Dataset summary:", dataset_summary_path)
print("- Zip:", local_zip_path)
print("- Google Drive latest:", DRIVE_LATEST_DIR)
print("- Google Drive latest model dir:", DRIVE_MODEL_DIR)
print("- Google Drive checkpoint dir:", DRIVE_CHECKPOINT_DIR)